apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
spec:
  selector:
    matchLabels:
      app: mosquitto
      type: back-end
  replicas: 1
  template:
    metadata:
      labels:
        app: mosquitto
        type: back-end
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto
        imagePullPolicy: Always        
        ports:        
        - containerPort: 1883
        volumeMounts:
        - name: nfs-persistent-volume
          mountPath: /mosquitto/config
          subPath: mqtt/config        
        - name: nfs-persistent-volume
          mountPath: /mosquitto/data
          subPath: mqtt/data
        - name: nfs-persistent-volume
          mountPath: /mosquitto/log
          subPath: mqtt/log
      volumes:
      - name: nfs-persistent-volume
        persistentVolumeClaim:
          claimName: nfs-persistent-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
spec:
  type: ClusterIP
  ports:  
  - port: 1883
  selector:
    app: mosquitto
    type: back-end
