apiVersion: v1
kind: Service
metadata:
  name: mqtt-ingress
  labels:
    app: mosquitto
    type: back-end
spec:
  type: LoadBalancer
  selector:
    app: mosquitto
    type: back-end
  ports:
  - port: 1883
    targetPort: 1883