apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql 
        image: linuxserver/mariadb
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Asia/Calcutta"
        - name: MYSQL_ROOT_PASSWORD
          value: "my-root-password"
        - name: MYSQL_DATABASE
          value: "dbSL"
        - name: MYSQL_USER
          value: "my-user"
        - name: MYSQL_PASSWORD
          value: "my-password"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: nfs-persistent-volume
          mountPath: /config
          subPath: mysql
      volumes:
      - name: nfs-persistent-volume
        persistentVolumeClaim:
          claimName: nfs-persistent-volume-claim
