apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ClusterIP
  ports:
  - port: 3306
  selector:
    app: mysql
    type: back-end
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
    type: back-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql 
        image: jsurf/rpi-mariadb
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: nfs-persistent-volume
          mountPath: /var/lib/mysql
          subPath: mysql
      volumes:
      - name: nfs-persistent-volume
        persistentVolumeClaim:
          claimName: nfs-persistent-volume-claim
