apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:      
      storage: 30Gi
